version: '3.8'

services:
  taskgoal-api:
    container_name: taskgoal-api 
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    networks:
      - task-network
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env.production
    networks:
      - task-network
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db

networks:
  task-network:
    driver: bridge